import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './inc/Header'
import Footer from './inc/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Saliha Nur Can',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
          <main>
            {children}
          </main>
        <Footer />
      </body>
    </html>
  )
}
